import { mkdir, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const projectRoot = fileURLToPath(new URL('..', import.meta.url))
const outputDirectory = path.join(projectRoot, 'src/assets/cafe/optimized')
const photos = [
  ['heartLakeImage', 'ankersee-herzsee', 'src/assets/cafe/ankersee-herzsee.jpeg'],
  ['lakeAerialImage', 'ankersee-luftaufnahme', 'src/assets/cafe/ankersee-luftaufnahme.jpeg'],
  ['cafeExteriorImage', 'cafe-aussen', 'src/assets/cafe/cafe-aussen.jpeg'],
  ['hallEntranceImage', 'fachwerk-eingang', 'src/assets/cafe/fachwerk-eingang.jpeg'],
  ['hallInteriorImage', 'diele-innenraum', 'BIlder/diele/diele_03.jpg'],
  ['gardenPanoramaImage', 'garten-kastanienbaum-panorama', 'src/assets/cafe/garten-kastanienbaum-panorama.jpeg'],
  ['gardenLakeImage', 'garten-seeblick', 'src/assets/cafe/garten-seeblick.jpeg'],
  ['gardenTerraceImage', 'garten-terrasse-panorama', 'src/assets/cafe/garten-terrasse-panorama.jpeg'],
  ['guestRoomPanoramaImage', 'gaststube-panorama', 'src/assets/cafe/gaststube-panorama.jpeg'],
  ['guestRoomImage', 'gaststube', 'src/assets/cafe/gaststube.jpeg'],
  ['peachCakeImage', 'pfirsich-buttermilch', 'src/assets/cafe/pfirsich-buttermilch.jpeg'],
  ['gooseberryCakeImage', 'stachelbeer-baiser', 'src/assets/cafe/stachelbeer-baiser.jpeg'],
  ['natureParkPartnerImage', 'naturpark-partner', 'BIlder/images/Signet_Naturpark-Partner_Web.jpg'],
]

await mkdir(outputDirectory, { recursive: true })

const imports = []
const imageDeclarations = []
const report = []

for (const [exportName, basename, relativeSource] of photos) {
  const source = path.join(projectRoot, relativeSource)
  const metadata = await sharp(source).metadata()
  const rotated = [5, 6, 7, 8].includes(metadata.orientation)
  const originalWidth = rotated ? metadata.height : metadata.width
  const originalHeight = rotated ? metadata.width : metadata.height
  const requestedWidths = basename === 'naturpark-partner' ? [200, 400] : [480, 800, 1200, 1600]
  const widths = [...new Set(requestedWidths.map((width) => Math.min(width, originalWidth)))]
  const sizes = []

  for (const width of widths) {
    const filename = `${basename}-${width}.webp`
    const output = path.join(outputDirectory, filename)
    const info = await sharp(source)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .toColourspace('srgb')
      .webp({ quality: 78, effort: 6 })
      .toFile(output)

    const importName = `${exportName}${width}`
    imports.push(`import ${importName} from './assets/cafe/optimized/${filename}'`)
    sizes.push({ width: info.width, bytes: info.size, importName })
  }

  const defaultImage = sizes.find((image) => image.width >= 800) ?? sizes.at(-1)
  const largestImage = sizes.at(-1)
  imageDeclarations.push(
    `export const ${exportName}: CafeImage = {\n` +
    `  src: ${defaultImage.importName},\n` +
    `  srcSet: [${sizes.map((image) => `${image.importName} + ' ${image.width}w'`).join(', ')}].join(', '),\n` +
    `  width: ${originalWidth},\n` +
    `  height: ${originalHeight},\n` +
    `}`,
  )

  const originalBytes = (await stat(source)).size
  report.push({
    name: basename,
    originalBytes,
    largestBytes: largestImage.bytes,
    smallBytes: sizes[0].bytes,
    reductionPercent: Math.round((1 - largestImage.bytes / originalBytes) * 100),
    widths: sizes.map((image) => image.width),
  })
}

const moduleSource = '// Generated by npm run images:optimize. Keep edits in scripts/optimize-images.mjs.\n' +
  imports.join('\n') + '\n\n' +
  'export type CafeImage = {\n  src: string\n  srcSet: string\n  width: number\n  height: number\n}\n\n' +
  imageDeclarations.join('\n\n') + '\n'

await writeFile(path.join(projectRoot, 'src/cafeImages.ts'), moduleSource)

const totals = report.reduce((total, image) => ({
  originalBytes: total.originalBytes + image.originalBytes,
  largestBytes: total.largestBytes + image.largestBytes,
  smallBytes: total.smallBytes + image.smallBytes,
}), { originalBytes: 0, largestBytes: 0, smallBytes: 0 })

console.log(JSON.stringify({ images: report, totals }, null, 2))
