// Generated by npm run images:optimize. Keep edits in scripts/optimize-images.mjs.
import lakeAerialImage480 from './assets/cafe/optimized/ankersee-luftaufnahme-480.webp'
import lakeAerialImage800 from './assets/cafe/optimized/ankersee-luftaufnahme-800.webp'
import lakeAerialImage1200 from './assets/cafe/optimized/ankersee-luftaufnahme-1200.webp'
import lakeAerialImage1280 from './assets/cafe/optimized/ankersee-luftaufnahme-1280.webp'
import cafeExteriorImage480 from './assets/cafe/optimized/cafe-aussen-480.webp'
import cafeExteriorImage800 from './assets/cafe/optimized/cafe-aussen-800.webp'
import cafeExteriorImage1200 from './assets/cafe/optimized/cafe-aussen-1200.webp'
import cafeExteriorImage1600 from './assets/cafe/optimized/cafe-aussen-1600.webp'
import hallEntranceImage480 from './assets/cafe/optimized/fachwerk-eingang-480.webp'
import hallEntranceImage800 from './assets/cafe/optimized/fachwerk-eingang-800.webp'
import hallEntranceImage1200 from './assets/cafe/optimized/fachwerk-eingang-1200.webp'
import hallEntranceImage1600 from './assets/cafe/optimized/fachwerk-eingang-1600.webp'
import hallInteriorImage480 from './assets/cafe/optimized/diele-innenraum-480.webp'
import hallInteriorImage600 from './assets/cafe/optimized/diele-innenraum-600.webp'
import gardenPanoramaImage480 from './assets/cafe/optimized/garten-kastanienbaum-panorama-480.webp'
import gardenPanoramaImage800 from './assets/cafe/optimized/garten-kastanienbaum-panorama-800.webp'
import gardenPanoramaImage1200 from './assets/cafe/optimized/garten-kastanienbaum-panorama-1200.webp'
import gardenPanoramaImage1600 from './assets/cafe/optimized/garten-kastanienbaum-panorama-1600.webp'
import gardenLakeImage480 from './assets/cafe/optimized/garten-seeblick-480.webp'
import gardenLakeImage800 from './assets/cafe/optimized/garten-seeblick-800.webp'
import gardenLakeImage1200 from './assets/cafe/optimized/garten-seeblick-1200.webp'
import gardenLakeImage1600 from './assets/cafe/optimized/garten-seeblick-1600.webp'
import gardenTerraceImage480 from './assets/cafe/optimized/garten-terrasse-panorama-480.webp'
import gardenTerraceImage800 from './assets/cafe/optimized/garten-terrasse-panorama-800.webp'
import gardenTerraceImage1200 from './assets/cafe/optimized/garten-terrasse-panorama-1200.webp'
import gardenTerraceImage1600 from './assets/cafe/optimized/garten-terrasse-panorama-1600.webp'
import guestRoomPanoramaImage480 from './assets/cafe/optimized/gaststube-panorama-480.webp'
import guestRoomPanoramaImage800 from './assets/cafe/optimized/gaststube-panorama-800.webp'
import guestRoomPanoramaImage1200 from './assets/cafe/optimized/gaststube-panorama-1200.webp'
import guestRoomPanoramaImage1600 from './assets/cafe/optimized/gaststube-panorama-1600.webp'
import guestRoomImage480 from './assets/cafe/optimized/gaststube-480.webp'
import guestRoomImage800 from './assets/cafe/optimized/gaststube-800.webp'
import guestRoomImage1200 from './assets/cafe/optimized/gaststube-1200.webp'
import guestRoomImage1600 from './assets/cafe/optimized/gaststube-1600.webp'
import peachCakeImage480 from './assets/cafe/optimized/pfirsich-buttermilch-480.webp'
import peachCakeImage800 from './assets/cafe/optimized/pfirsich-buttermilch-800.webp'
import peachCakeImage1200 from './assets/cafe/optimized/pfirsich-buttermilch-1200.webp'
import peachCakeImage1600 from './assets/cafe/optimized/pfirsich-buttermilch-1600.webp'
import gooseberryCakeImage480 from './assets/cafe/optimized/stachelbeer-baiser-480.webp'
import gooseberryCakeImage800 from './assets/cafe/optimized/stachelbeer-baiser-800.webp'
import gooseberryCakeImage1200 from './assets/cafe/optimized/stachelbeer-baiser-1200.webp'
import gooseberryCakeImage1600 from './assets/cafe/optimized/stachelbeer-baiser-1600.webp'
import natureParkPartnerImage200 from './assets/cafe/optimized/naturpark-partner-200.webp'
import natureParkPartnerImage400 from './assets/cafe/optimized/naturpark-partner-400.webp'

export type CafeImage = {
  src: string
  srcSet: string
  width: number
  height: number
}

export const lakeAerialImage: CafeImage = {
  src: lakeAerialImage800,
  srcSet: [lakeAerialImage480 + ' 480w', lakeAerialImage800 + ' 800w', lakeAerialImage1200 + ' 1200w', lakeAerialImage1280 + ' 1280w'].join(', '),
  width: 1280,
  height: 902,
}

export const cafeExteriorImage: CafeImage = {
  src: cafeExteriorImage800,
  srcSet: [cafeExteriorImage480 + ' 480w', cafeExteriorImage800 + ' 800w', cafeExteriorImage1200 + ' 1200w', cafeExteriorImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 1200,
}

export const hallEntranceImage: CafeImage = {
  src: hallEntranceImage800,
  srcSet: [hallEntranceImage480 + ' 480w', hallEntranceImage800 + ' 800w', hallEntranceImage1200 + ' 1200w', hallEntranceImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 1066,
}

export const hallInteriorImage: CafeImage = {
  src: hallInteriorImage600,
  srcSet: [hallInteriorImage480 + ' 480w', hallInteriorImage600 + ' 600w'].join(', '),
  width: 600,
  height: 450,
}

export const gardenPanoramaImage: CafeImage = {
  src: gardenPanoramaImage800,
  srcSet: [gardenPanoramaImage480 + ' 480w', gardenPanoramaImage800 + ' 800w', gardenPanoramaImage1200 + ' 1200w', gardenPanoramaImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 556,
}

export const gardenLakeImage: CafeImage = {
  src: gardenLakeImage800,
  srcSet: [gardenLakeImage480 + ' 480w', gardenLakeImage800 + ' 800w', gardenLakeImage1200 + ' 1200w', gardenLakeImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 1066,
}

export const gardenTerraceImage: CafeImage = {
  src: gardenTerraceImage800,
  srcSet: [gardenTerraceImage480 + ' 480w', gardenTerraceImage800 + ' 800w', gardenTerraceImage1200 + ' 1200w', gardenTerraceImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 536,
}

export const guestRoomPanoramaImage: CafeImage = {
  src: guestRoomPanoramaImage800,
  srcSet: [guestRoomPanoramaImage480 + ' 480w', guestRoomPanoramaImage800 + ' 800w', guestRoomPanoramaImage1200 + ' 1200w', guestRoomPanoramaImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 832,
}

export const guestRoomImage: CafeImage = {
  src: guestRoomImage800,
  srcSet: [guestRoomImage480 + ' 480w', guestRoomImage800 + ' 800w', guestRoomImage1200 + ' 1200w', guestRoomImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 1074,
}

export const peachCakeImage: CafeImage = {
  src: peachCakeImage800,
  srcSet: [peachCakeImage480 + ' 480w', peachCakeImage800 + ' 800w', peachCakeImage1200 + ' 1200w', peachCakeImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 1200,
}

export const gooseberryCakeImage: CafeImage = {
  src: gooseberryCakeImage800,
  srcSet: [gooseberryCakeImage480 + ' 480w', gooseberryCakeImage800 + ' 800w', gooseberryCakeImage1200 + ' 1200w', gooseberryCakeImage1600 + ' 1600w'].join(', '),
  width: 1600,
  height: 1200,
}

export const natureParkPartnerImage: CafeImage = {
  src: natureParkPartnerImage400,
  srcSet: [natureParkPartnerImage200 + ' 200w', natureParkPartnerImage400 + ' 400w'].join(', '),
  width: 400,
  height: 322,
}
