create extension if not exists pgcrypto with schema extensions;

create type public.reservation_area as enum ('inside', 'outside');
create type public.reservation_status as enum (
  'requested',
  'confirmed',
  'cancelled',
  'declined',
  'no_show'
);
create type public.reservation_source as enum ('online', 'phone', 'admin');

create table public.service_settings (
  singleton boolean primary key default true check (singleton),
  opens_at time not null default '12:00',
  closes_at time not null default '18:00',
  slot_interval_minutes integer not null default 60
    check (slot_interval_minutes between 15 and 240),
  reservation_duration_minutes integer not null default 60
    check (reservation_duration_minutes between 30 and 480),
  minimum_notice_minutes integer not null default 120
    check (minimum_notice_minutes between 0 and 10080),
  booking_horizon_days integer not null default 180
    check (booking_horizon_days between 1 and 730),
  maximum_party_size integer not null default 60
    check (maximum_party_size between 1 and 200),
  updated_at timestamptz not null default now()
);

insert into public.service_settings (singleton) values (true);

create table public.cafe_tables (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 1 and 80),
  area public.reservation_area not null,
  seats integer not null check (seats between 1 and 60),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.service_exceptions (
  service_date date primary key,
  is_open boolean not null,
  opens_at time,
  closes_at time,
  note text check (char_length(note) <= 500),
  created_at timestamptz not null default now(),
  check (
    (is_open and opens_at is not null and closes_at is not null and opens_at < closes_at)
    or (not is_open)
  )
);

create table public.reservations (
  id uuid primary key default gen_random_uuid(),
  table_id bigint references public.cafe_tables(id),
  area public.reservation_area not null,
  reservation_date date not null,
  start_time time not null,
  duration_minutes integer not null default 60
    check (duration_minutes between 30 and 480),
  guest_count integer not null check (guest_count between 1 and 60),
  customer_name text not null check (char_length(trim(customer_name)) between 2 and 120),
  customer_email text not null check (char_length(customer_email) <= 254),
  customer_phone text not null check (char_length(trim(customer_phone)) between 5 and 40),
  note text check (char_length(note) <= 2000),
  status public.reservation_status not null default 'requested',
  source public.reservation_source not null default 'online',
  cancellation_token_hash bytea,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cancelled_at timestamptz,
  check (reservation_date >= date '2020-01-01')
);

create table public.blocked_slots (
  id bigint generated by default as identity primary key,
  service_date date not null,
  start_time time not null,
  end_time time not null,
  area public.reservation_area,
  table_id bigint references public.cafe_tables(id) on delete cascade,
  reason text check (char_length(reason) <= 500),
  created_at timestamptz not null default now(),
  check (start_time < end_time)
);

create index reservations_schedule_idx
  on public.reservations (reservation_date, area, start_time, status);
create index reservations_table_schedule_idx
  on public.reservations (table_id, reservation_date, start_time)
  where status in ('requested', 'confirmed');
create index blocked_slots_schedule_idx
  on public.blocked_slots (service_date, area, start_time);

alter table public.service_settings enable row level security;
alter table public.cafe_tables enable row level security;
alter table public.service_exceptions enable row level security;
alter table public.reservations enable row level security;
alter table public.blocked_slots enable row level security;

revoke all on table public.service_settings from anon, authenticated;
revoke all on table public.cafe_tables from anon, authenticated;
revoke all on table public.service_exceptions from anon, authenticated;
revoke all on table public.reservations from anon, authenticated;
revoke all on table public.blocked_slots from anon, authenticated;

create or replace function public.easter_sunday(p_year integer)
returns date
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  a integer := p_year % 19;
  b integer := p_year / 100;
  c integer := p_year % 100;
  d integer := b / 4;
  e integer := b % 4;
  f integer := (b + 8) / 25;
  g integer := (b - f + 1) / 3;
  h integer;
  i integer := c / 4;
  k integer := c % 4;
  l integer;
  m integer;
  easter_month integer;
  easter_day integer;
begin
  h := (19 * a + b - d - g + 15) % 30;
  l := (32 + 2 * e + 2 * i - h - k) % 7;
  m := (a + 11 * h + 22 * l) / 451;
  easter_month := (h + l - 7 * m + 114) / 31;
  easter_day := ((h + l - 7 * m + 114) % 31) + 1;
  return make_date(p_year, easter_month, easter_day);
end;
$$;

create or replace function public.is_schleswig_holstein_holiday(p_date date)
returns boolean
language sql
immutable
set search_path = public, pg_temp
as $$
  select to_char(p_date, 'MM-DD') in (
    '01-01', '05-01', '10-03', '10-31', '12-25', '12-26'
  ) or p_date in (
    public.easter_sunday(extract(year from p_date)::integer) - 2,
    public.easter_sunday(extract(year from p_date)::integer) + 1,
    public.easter_sunday(extract(year from p_date)::integer) + 39,
    public.easter_sunday(extract(year from p_date)::integer) + 50
  );
$$;

create or replace function public.is_service_day(p_date date)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(
    (select is_open from public.service_exceptions where service_date = p_date),
    extract(isodow from p_date) in (6, 7)
      or public.is_schleswig_holstein_holiday(p_date)
  );
$$;

create or replace function public.get_available_slots(
  p_date date,
  p_area text,
  p_guests integer
)
returns table (slot_time time, available boolean)
language plpgsql
stable
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_area public.reservation_area;
  v_settings public.service_settings%rowtype;
  v_opens_at time;
  v_closes_at time;
begin
  if p_area not in ('inside', 'outside') or p_guests is null or p_guests < 1 then
    return;
  end if;

  select * into v_settings from public.service_settings where singleton;
  if not found or p_guests > v_settings.maximum_party_size then
    return;
  end if;

  if p_date < current_date
    or p_date > current_date + v_settings.booking_horizon_days
    or not public.is_service_day(p_date) then
    return;
  end if;

  v_area := p_area::public.reservation_area;
  select
    coalesce(se.opens_at, v_settings.opens_at),
    coalesce(se.closes_at, v_settings.closes_at)
  into v_opens_at, v_closes_at
  from (select 1) seed
  left join public.service_exceptions se on se.service_date = p_date;

  return query
  select candidate.slot_time,
    exists (
      select 1
      from public.cafe_tables t
      where t.active
        and t.area = v_area
        and t.seats >= p_guests
        and not exists (
          select 1
          from public.reservations r
          where r.table_id = t.id
            and r.reservation_date = p_date
            and r.status in ('requested', 'confirmed')
            and r.start_time < candidate.slot_time
              + make_interval(mins => v_settings.reservation_duration_minutes)
            and r.start_time + make_interval(mins => r.duration_minutes)
              > candidate.slot_time
        )
        and not exists (
          select 1
          from public.blocked_slots b
          where b.service_date = p_date
            and (b.area is null or b.area = v_area)
            and (b.table_id is null or b.table_id = t.id)
            and b.start_time < candidate.slot_time
              + make_interval(mins => v_settings.reservation_duration_minutes)
            and b.end_time > candidate.slot_time
        )
    ) as available
  from generate_series(
    p_date + v_opens_at,
    p_date + v_closes_at
      - make_interval(mins => v_settings.reservation_duration_minutes),
    make_interval(mins => v_settings.slot_interval_minutes)
  ) generated_slot
  cross join lateral (select generated_slot::time as slot_time) candidate
  where generated_slot >= now() + make_interval(mins => v_settings.minimum_notice_minutes)
  order by candidate.slot_time;
end;
$$;

create or replace function public.create_reservation(
  p_area text,
  p_date date,
  p_time time,
  p_guests integer,
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_note text default null
)
returns table (
  reservation_id uuid,
  reservation_status public.reservation_status,
  cancellation_token text
)
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_area public.reservation_area;
  v_settings public.service_settings%rowtype;
  v_opens_at time;
  v_closes_at time;
  v_table_id bigint;
  v_token text;
  v_reservation_id uuid;
begin
  if p_area not in ('inside', 'outside') then
    raise exception 'invalid_area' using errcode = '22023';
  end if;
  v_area := p_area::public.reservation_area;

  select * into v_settings from public.service_settings where singleton;
  if not found
    or p_guests is null
    or p_guests < 1
    or p_guests > v_settings.maximum_party_size
    or char_length(trim(coalesce(p_customer_name, ''))) not between 2 and 120
    or char_length(trim(coalesce(p_customer_phone, ''))) not between 5 and 40
    or p_customer_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
    or char_length(p_customer_email) > 254
    or char_length(coalesce(p_note, '')) > 2000 then
    raise exception 'invalid_reservation_data' using errcode = '22023';
  end if;

  select
    coalesce(se.opens_at, v_settings.opens_at),
    coalesce(se.closes_at, v_settings.closes_at)
  into v_opens_at, v_closes_at
  from (select 1) seed
  left join public.service_exceptions se on se.service_date = p_date;

  if p_date < current_date
    or p_date > current_date + v_settings.booking_horizon_days
    or not public.is_service_day(p_date)
    or p_time < v_opens_at
    or p_time + make_interval(mins => v_settings.reservation_duration_minutes)
      > v_closes_at
    or mod(
      extract(epoch from (p_time - v_opens_at))::integer / 60,
      v_settings.slot_interval_minutes
    ) <> 0
    or (p_date + p_time) < now() + make_interval(mins => v_settings.minimum_notice_minutes) then
    raise exception 'invalid_reservation_time' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_date::text || ':' || p_time::text || ':' || p_area, 0)
  );

  select t.id into v_table_id
  from public.cafe_tables t
  where t.active
    and t.area = v_area
    and t.seats >= p_guests
    and not exists (
      select 1
      from public.reservations r
      where r.table_id = t.id
        and r.reservation_date = p_date
        and r.status in ('requested', 'confirmed')
        and r.start_time < p_time
          + make_interval(mins => v_settings.reservation_duration_minutes)
        and r.start_time + make_interval(mins => r.duration_minutes) > p_time
    )
    and not exists (
      select 1
      from public.blocked_slots b
      where b.service_date = p_date
        and (b.area is null or b.area = v_area)
        and (b.table_id is null or b.table_id = t.id)
        and b.start_time < p_time
          + make_interval(mins => v_settings.reservation_duration_minutes)
        and b.end_time > p_time
    )
  order by t.seats, t.sort_order, t.id
  limit 1
  for update of t;

  if v_table_id is null then
    raise exception 'slot_unavailable' using errcode = 'P0001';
  end if;

  v_token := encode(extensions.gen_random_bytes(24), 'hex');

  insert into public.reservations (
    table_id,
    area,
    reservation_date,
    start_time,
    duration_minutes,
    guest_count,
    customer_name,
    customer_email,
    customer_phone,
    note,
    source,
    cancellation_token_hash
  ) values (
    v_table_id,
    v_area,
    p_date,
    p_time,
    v_settings.reservation_duration_minutes,
    p_guests,
    trim(p_customer_name),
    lower(trim(p_customer_email)),
    trim(p_customer_phone),
    nullif(trim(coalesce(p_note, '')), ''),
    'online',
    extensions.digest(v_token, 'sha256')
  )
  returning id into v_reservation_id;

  return query select v_reservation_id, 'requested'::public.reservation_status, v_token;
end;
$$;

create or replace function public.cancel_reservation(
  p_reservation_id uuid,
  p_cancellation_token text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_updated integer;
begin
  if p_cancellation_token is null or char_length(p_cancellation_token) <> 48 then
    return false;
  end if;

  update public.reservations
  set status = 'cancelled', cancelled_at = now(), updated_at = now()
  where id = p_reservation_id
    and status in ('requested', 'confirmed')
    and cancellation_token_hash = extensions.digest(p_cancellation_token, 'sha256');

  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

revoke all on function public.easter_sunday(integer) from public;
revoke all on function public.is_schleswig_holstein_holiday(date) from public;
revoke all on function public.is_service_day(date) from public;
revoke all on function public.get_available_slots(date, text, integer) from public;
revoke all on function public.create_reservation(text, date, time, integer, text, text, text, text) from public;
revoke all on function public.cancel_reservation(uuid, text) from public;

grant execute on function public.get_available_slots(date, text, integer) to anon, authenticated;
grant execute on function public.create_reservation(text, date, time, integer, text, text, text, text) to anon, authenticated;
grant execute on function public.cancel_reservation(uuid, text) to anon, authenticated;

comment on table public.cafe_tables is 'Konfigurierbare Tische im Innen- und Außenbereich.';
comment on table public.reservations is 'Online, telefonisch oder intern angelegte Reservierungen.';
comment on table public.service_exceptions is 'Sonderöffnungen und Schließtage überschreiben Wochenenden und Feiertage.';
comment on function public.create_reservation is 'Legt eine Reservierung atomar auf dem kleinsten passenden freien Tisch an.';
